[[constraint]]
  branch = "master"
  name = "github.com/andybalholm/cascadia"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/carlmjohnson/gracefulserver"
  version = "0.1.0"
